using Test
#import Pkg; Pkg.add("LinearAlgebraicRepresentation")

include("./Box.jl")
include("./Frustum.jl")
include("./Geometry.jl")
#include("./GLColorBuffer.jl")
#include("./GLMesh.jl")
#include("./GLPhongShader.jl")
#include("./GLShader.jl")
#include("./GLText.jl")
#include("./GLUtils.jl")
#include("./GLVertexArray.jl")
#include("./GLVertexBuffer.jl")
#include("./Matrix.jl")
#include("./Point.jl")
#include("./Quaternion.jl")
#include("./Viewer.jl")
#include("./ViewerGL.jl")
